### ISSUE TITLE
Thanks for your Viscosity password blog!

### ISSUE THREAD

**Issue by HumanEquivalentUnit** [checkymander/checkymander.github.io#1]
Helped enormously; I was getting credentials out of Veeam (coincidentally like your other blog) and some of them would not decrypt, giving Invalid Data errors, and I used your blog to debug Veeam and pull the data out of the `CryptUnprotectData()` arguments. 

I couldn't have got through that on my own! 

In case it's of any interest, here's how I combined the two approaches:

Edit the registry to make Windows start the Veeam service in a debugger, by adding this:

```
(new key)
HKLM\Software\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\Veeam.Backup.Service.exe\

(inside it, a string type named) "Debugger"
(value) "C:\Program Files\Debugging Tools for Windows (x64)\cdb.exe" -server tcp:port=9999
```

Then start the service (and ignore the "starting" dialog, it will never finish); cdb.exe runs in the background listening on a socket; connect with:

```powershell
PS C:\Program Files\Debugging Tools for Windows (x64)> .\windbg.exe -remote tcp:port=9999
```

and Veeam is there waiting, running and paused. Follow your blog to `bp Crypt32!CryptUnprotectData` then `g` and it hit the breakpoint several times while starting up. I looked for an Entropy value. There was one for one of the passwords, but the one I wanted had none. I instead looked at the DATA_BLOB for the first argument `*pDataIn` in register `rcx` and found the data passed to the function to decrypt was 64-bytes longer than the bytes from the Base64 password string in the Veeam database. Copying the full data from this blob, I could decrypt it. I don't know where the extra comes from, a hash or salt I imagine; it wasn't recognisable text.

Incidentally, I couldn't use SharpDPAPI as it triggered my AV on download, but I could decrypt directly from PowerShell with:

```powershell
[System.Reflection.Assembly]::LoadWithPartialName('System.Security.Cryptography')    # Add-Type -AssemblyName System.Security in newer PowerShell
$Base64Password = "Insert-VeeamDB-Base64-Password-here"
$encryptedBytes = [Convert]::FromBase64String($Base64Password)
# (append salted bytes to $encryptedBytes here)
$unprotected = [System.Security.Cryptography.ProtectedData]::Unprotect($encryptedBytes, $null, 'LocalMachine')
[System.Text.Encoding]::UTF8.GetString($unprotected)
```

**Comment by checkymander** [comment]
That's awesome research there, definitely might be worth a blog post of your own!
